import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tasky</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="task.svg" />
      </Head>
      <section className=" text-red-500">main</section>
    </>
  );
}
