import Head from "next/head";
import Image from "next/image";
import icon from "@/assets/play.svg"

export default function Home() {
  return (
    <>
      <Head>
        <title>Tasky</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="task.svg" />
      </Head>
      <div className="container px-5 pt-6">
         <div className="row-1 flex justify-between items-center">
            <div className="time">
               <h2 className=" text-[30px] font-bold">Today</h2>
               <span className=" text-[15px]">Mon 22, 2021 | 10:00 AM</span>
            </div>
            <div className="timer bg-white flex items-center py-[30px] px-[20px] rounded-[20px]">
               <h5>Start Time Tracker</h5>
               <div className="btn bg-yellow-300 flex justify-center items-center h-[40px] w-[40px] rounded-md ml-8 cursor-pointer">
                  <Image src={icon} alt={'icon'} height={20} width={20}/>
               </div>
            </div>
         </div>
      </div>
    </>
  );
}
